### ISSUE TITLE
Add API only option which optimizes for when only running as API. 

### ISSUE THREAD

**Issue by zachferland** [3box/3box-pinning-node#110]
An optimization, before, but also required now. Can open a store to read it and then close it as soon as done when using only api.

**Comment by oed** [comment]
I think here we can also set replicate to false so that it doesn't try to make updates. Alternatively, make sure that we don't connect to any other ipfs nodes.

**Comment by zachferland** [comment]
yeah it won't connect to any other nodes, only port 80 traffic is let through from load balancer to subnet. But probably good if we can configure instead, so that it is not so environment specific.
