### ISSUE TITLE
(scaling branch) Bug: Error thrown finding ipfs repo which crashes node

### ISSUE THREAD

**Issue by zachferland** [3box/3box-pinning-node#111]
Error: ENOENT: no such file or directory, lstat '/jsipfs'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! 3box-pinning-server@1.1.0 start: `node ./src/node.js`

Doesn't happen all of the time, must be some race condition, must not be initializing s3 modules entirely before calls are made against it. Seems to only happen on start, but would have to confirm.

**Comment by zachferland** [comment]
Looked through additional logs, does not only happen on starts, fails randomly at later points as well.

**Comment by zachferland** [comment]
Oh just the disk usage measurement metric! Not a bug, but leaving story as reminder to change some measurements, and remove ones that don't make sense anymore.

**Comment by oed** [comment]
Heh, was worried there for a while 😆

**Comment by zachferland** [comment]
Replaced with - https://github.com/3box/3box-pinning-node/issues/113 

Closing now
