### ISSUE TITLE
Change disk usage/memory measurement metric

### ISSUE THREAD

**Issue by zachferland** [3box/3box-pinning-node#113]
In new arch, don't to measure from machine (and some measurement not longer relevant), unless we still want to report the data in a different way. Instead ECS can monitor and have rules to deal with memory getting too large.

**Comment by zachferland** [comment]
Also related, adding to this story
 - add necessary metric ENV vars and keys 
 - add logic like before, once container memory getting to 80% capacity, restart another

**Comment by oed** [comment]
That sounds great :)
