### ISSUE TITLE
[BUG] Thread API hanging (NGINX 504) 

### ISSUE THREAD

**Issue by zachferland** [3box/3box-pinning-node#116]
Originally reported by kenzo yesterday, ie 
- https://ipfs.3box.io/thread?space=threeBoxTest&name=subdexThread

Look at it a bit, but haven't followed through on it yet. 

---

Another example 
https://ipfs.3box.io/thread?space=socialite&name=decentralized

**Comment by zachferland** [comment]
One part of this is the node doesn't have a good way of determining if a threads exists. If the manifest file can't be found on ipfs, it just hangs loading the file indefinitely. Determine address doesn't save the manifest file. We know the access controller, thus manifest right now, so could still load this way, but wont in the future. At the very least we should time out, so it doesn't hang for ever, timeout can be pretty short at moment, since expected to fine manifest on our local ipfs node if it does exist.

The second half of this, not being able to fetch threads that do exist and have data, I can't replicate locally, only seeing production. But failure looks same as if the thread didnt exist at all.

**Comment by oed** [comment]
I see. I think we can resolve this by calling the following function with `onlyHash = false` https://github.com/orbitdb/orbit-db/blob/master/src/OrbitDB.js#L241

**Comment by zachferland** [comment]
yeah exactly! saw that before, that's the solution for that part for now, but need some thing else in the future (like timeout or something)

**Comment by zachferland** [comment]
might need timeout for other api calls after as well, once trying to just open a space, or some single db, right now most calls can tell if store exists, by if address link exists and then if in the root store

**Comment by oed** [comment]
Yeah, we might need to rethink the logic of how threads are created and referenced in the full version of threads.

**Comment by zachferland** [comment]
uhhhh, well that was easy on revisiting, always forget about nginx, threads path just was not being redirected anywhere, hence of course why it worked locally

**Comment by zachferland** [comment]
https://github.com/3box/3box-devops/pull/17

**Comment by oed** [comment]
:S Nice you found it though !

**Comment by zachferland** [comment]
This was resolved by pr already merged here and in devops
