### ISSUE TITLE
[New Arch] Bug - First requests to get profiles to API fail

### ISSUE THREAD

**Issue by zachferland** [3box/3box-pinning-node#123]
Deploy a new instance of arch, run all data migrations, to migrate production data to this instance. You can clear you browser cache, and then open box, this all works, its able to get all the migrated data. 

If you call getProfile on a profile though before they open their box, then it hangs. As soon as you open as above, even when making sure to not share cached data from browser, then the api works after. 

So what is the difference in open first time in lib with no data vs opening first time on pinning node?

**Comment by zachferland** [comment]
Was finally able to replicate this reliably and pinpoint. Tested by running a migration to a local instance instead of aws infra, then was able to finally iterate faster. Its definitely due to an issue in ipfs s3 datastore. I was able to run everything perfectly against all accounts i was trying before, by 1) migrating orbitdb data to local redis instance, and then by migrating ipfs data to local node (not in s3, just in fs). Then when i changed it to an s3 instance of the exact same data prior, i saw all the same errors i saw on deployed infra. 

Two paths forward
- find issue in ipfs s3 datastore (would like to find it, but already found another bug, likely just not too stable yet) 
- mount a shared filesystem to the nodes (EFS, longterm not required for our needs, and multiple the price, but likely more reliable in short term)

**Comment by oed** [comment]
Great that you found it. Is this happening always? i.e. when only one node is connected to s3, or only when we also connect the api nodes?
1. How difficult do you think it would be to resolve the issue with s3 datastore?
1. What is the other bug you found?
1. Does it seem like efs would be easy to set up? Could there be potential hiccups there as well?

**Comment by zachferland** [comment]
Alright went through all the easy issues we talked about, and it is the migration, s3 data stores just the block data in a slightly different way. I remember looking to make sure this wasnt the case a few weeks ago, but i guessed it was missed, and when you are testing all the same accounts, it actually ended up finding most of the data eventually. So was only more obvious when starting right from new migration. 

So luckily, not to difficult of in issue, won't be hard to map one structure to the other. Need to also confirm it wasn't some change in the ipfs s3 lib or config.

**Comment by zachferland** [comment]
Resolved with - https://github.com/3box/ipfs-fs-to-s3-datastore

A cli utlity to transfer ipfs fs datastore data to a ipfs S3 datastore, transforms data to format for s3, and then syncs data to s3.
