### ISSUE TITLE
Get Follower / Contact thread by passing address, not with Box object

### ISSUE THREAD

**Issue by oznekenzo** [3box/3box-pinning-node#153]
right now we are getting the following thread using the Box object which has your ethereum address you use to login with.
But when followers becomes something belonging specifically and only to a users eth address, we will want to get that public info without using the Box object.
So I as user A visits user Bs profile, the page needs to load Bs followers, but obviously I cant do that with my own Box object.
Currently theres no way to get a thread by passing just an address

**Comment by oed** [comment]
All threads should be listed in the data that is present in `Box.getSpace`. There you will get access to all the parameters required to get the thread by `Box.getThread`.

cc @zachferland

**Comment by oznekenzo** [comment]
@oed but what about getting someone else's Following thread?

**Comment by oed** [comment]
Should be possible in the same manner!

**Comment by michaelsena** [comment]
Should be covered by other stories, but keeping open to be sure.
