### ISSUE TITLE
getProfiles with 3IDs

### ISSUE THREAD

**Issue by oed** [3box/3box-pinning-node#155]
3IDs use uncompressed keys, while muport doesn't.

**Comment by zachferland** [comment]
@oed whats the easiest way to go from 3ID -> root store address?

**Comment by oed** [comment]
@zachferland should be the same way as is already implemented for muport. Only difference is that we shouldn't call the `uncompressSECP256K1Key` function. All the code is in the Utils module.

**Comment by zachferland** [comment]
yeah saw the keys, got the same from both, but rootstore address derived from muport did

**Comment by oed** [comment]
@zachferland I'm not sure I'm following exactly. What is the problem you have with it?
