### ISSUE TITLE
Internal Multi Write Node Scaling 

### ISSUE THREAD

**Issue by zachferland** [3box/3box-pinning-node#206]
Will be broken down into separate stories in epic, here is the rough outline

- Connect multi nodes, and setup local env to test this, or remote env to test effectively. Testing will be pretty important for this feature to confidently move forward. 
- Separate out the libp2p parts of orbitdb into own logical transport. Basically it just handling a few events differently, not to hard to plug in replication events from our own transport. Can even use libp2p at first. 
- Setup internal message que, and way to test/mock the same locally
- Improve internal message que logic. Only subscribing to messages when db open, etc 
- New infra definitions, test, deploy

**Comment by michaelsena** [comment]
closing, reflected in other issues
