### ISSUE TITLE
getThread() does not return Author, but joinThread() with getPosts() does

### ISSUE THREAD

**Issue by oznekenzo** [3box/3box-pinning-node#213]
'Author' is not returned from static getThread method, and is necessary for the 3box-comments component - otherwise a user will have to sign to open every unopened space upon landing on a page with comments (instead of signing on Comment post)

**Comment by oed** [comment]
If you feel like addressing this @oznekenzo the fix should be fairly simple.

On this line:
https://github.com/3box/3box-pinning-node/blob/develop/src/pinning.js#L253
We need to get the author like this:
https://github.com/3box/3box-js/blob/develop/src/thread.js#L145

**Comment by oed** [comment]
This has been fixed. Closing.
