### ISSUE TITLE
Update to OrbitDB v0.22

### ISSUE THREAD

**Issue by oed** [3box/3box-pinning-node#238]
Test to make sure:
* We can read old data
* We can communicate with 3box-js that's using the previous version of orbitdb

**Comment by zachferland** [comment]
Test our redis orbit cache implementation, may need to change mapping func, but data in store will stay the same. 

Likely didn't change but test internal messaging layer module, since not using exposed orbit api. 

Higher points for uncertainty about our custom implementation parts.
