### ISSUE TITLE
Investigate if we can use peer.exchanged event

### ISSUE THREAD

**Issue by oed** [3box/3box-pinning-node#258]
Instead of sending the number of entries.

https://github.com/orbitdb/orbit-db-store/pull/38

**Comment by zachferland** [comment]
Also - https://github.com/orbitdb/orbit-db/pull/606

**Comment by zachferland** [comment]
Some what, it will simply emit an event for when heads have been exchanged/received from a peer. But then on the client side for the same functionality we would have to await that event, and then await till the logs loads entries up to those heads (or includes those heads), to resolve sync done. May be a little more complex in 3box-js, but probs worth if from pinning node perspective, since this would be as fast as new current changes to share number entries, and wouldnt require an additional storage layers or persistent stores. And not additional message would be passed.

**Comment by oed** [comment]
Hm, I was under the impression that the event is only triggered after heads have been exchanged and they are loaded into the log!

**Comment by zachferland** [comment]
yes! see it,  hmm even though you shared that one before i mostly read the orbit-db pr, but yeah in that case we should definitely use. Seems like 38 shouldn't change current sync though, and should not block by heads, but return and then also consume cb to call once heads sync to call peers.exchanged

**Comment by zachferland** [comment]
Also seems like this needs some work https://github.com/orbitdb/orbit-db-store/pull/38/files#diff-7a95c660669a260e384552aaa39be4bfR266 Seems like doesn't resolve specific to heads just received, but would continue to not resolve if there where additional heads sync with other peers at same time. But maybe no big deal, if not blocked (like said above), and would work well for us anyways.

**Comment by oed** [comment]
cc @msterle 
For: https://github.com/3box/3box/issues/876

**Comment by msterle** [comment]
@zachferland Is that the same limitation described in the commit message [here](https://github.com/orbitdb/orbit-db-store/pull/38/commits/ddac2ad7dbd4e57c1045237255b653eda10d8910)?

**Comment by zachferland** [comment]
oh yeah! didn't see that, but i was also saying in first comment, that maybe it shouldnt change the resolution of sync, but just emit that additional event upon that condition. Then it would be almost entirely minimized, the current meaning of sync wouldnt change and wouldnt be blocked, then we get the additional event which is not a big deal it was blocked. But yeah also overall, this is not likely  (at least now) and will eventually resolve (as said there)

**Comment by zachferland** [comment]
^think this is likely worth it, but yeah the changes need to meet condition in commit message are not really worth it (and to meet a case basically now seen today)

**Comment by michaelsena** [comment]
@msterle
