### ISSUE TITLE
Profile DB doesn't seem to be loading on pinning-node

### ISSUE THREAD

**Issue by oed** [3box/3box-pinning-node#271]
I've only seen this on one DB so far, but for that it's a pretty major issue since the DB isn't loading on the pinning-node so no `HAS_RESPONSE` is being sent for it. Furthermore, since it never ends up loading fully even if you make local updates they are not synced to the pinning-node.

Some observations below:
Querying profile clearly works:
```
https://ipfs.3box.io/profile?did=did:3:bafyreietqryrtsm7tgw6dghp3lbdrwuk3qim3gtidvxp64s2q2g4lvexuu
```
Loding rootstore doesn't work if you try to also sync public store (no response for public store HAS_ENTRIES).

Turns out the public store is not loading on the pinning-node:

Error message opening public store from prod pinning-node console:
```
Opening db: /orbitdb/QmW3feC2xSVL7dZzcRMKF4HJjtdZxHv5nfE7pwni6cgtpP/12200d2d8d787aa61cb724fd57048a79a8c7c8dab502baec9a26e003db384dab8e97.public
(node:27) UnhandledPromiseRejectionWarning: Error: Could not validate signature "3045022100bb22348762fd577e69f7161beb9d3324698b4d70b4aa9b78d0134bef8af698850220637c94ac7a712330388114e0ffc4ea69a335882358670314ac468a8e5ae1899c" for entry "zdpuAn1S1GoAcmtciJ916B4u6fQueRbbU9paKLJHbr6aMeeeb" and key "04f7c248b3805a86c53bb218c19c70778018cc35f0c56edaa55d5adc9e010160e5642f16b67b730984708942b4514f2e510d956a424acee0de97131e70fabcd16b"
at verify (/3box-pinning-server/node_modules/orbit-db-store/node_modules/ipfs-log/src/log.js:381:27)
at process._tickCallback (internal/process/next_tick.js:68:7)
(node:27) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

Looking at the entry where the error happens:
```js
box._ipfs.dag.get('zdpuAn1S1GoAcmtciJ916B4u6fQueRbbU9paKLJHbr6aMeeeb').then(x => console.log(JSON.stringify(x.value)))
```
Output:
```js
{
  "v":1,"id":"/orbitdb/QmW3feC2xSVL7dZzcRMKF4HJjtdZxHv5nfE7pwni6cgtpP/12200d2d8d787aa61cb724fd57048a79a8c7c8dab502baec9a26e003db384dab8e97.public",
  "key":"04f7c248b3805a86c53bb218c19c70778018cc35f0c56edaa55d5adc9e010160e5642f16b67b730984708942b4514f2e510d956a424acee0de97131e70fabcd16b",
  "sig":"3045022100bb22348762fd577e69f7161beb9d3324698b4d70b4aa9b78d0134bef8af698850220637c94ac7a712330388114e0ffc4ea69a335882358670314ac468a8e5ae1899c",
  "hash":null,"next":[{"codec":"dag-cbor","version":1,"hash":{"type":"Buffer","data":[18,32,150,151,104,164,209,179,237,246,50,121,113,80,255,199,155,89,101,131,125,77,30,7,61,220,170,11,94,249,121,201,22,21]}},{"codec":"dag-cbor","version":1,"hash":{"type":"Buffer","data":[18,32,253,6,218,155,168,233,215,208,2,32,40,144,30,209,203,216,116,91,166,165,136,223,26,62,25,196,181,115,218,90,93,7]}}],"clock":{"id":"04f7c248b3805a86c53bb218c19c70778018cc35f0c56edaa55d5adc9e010160e5642f16b67b730984708942b4514f2e510d956a424acee0de97131e70fabcd16b","time":3},
  "payload":{
    "op":"PUT",
    "key":"memberSince",
    "value":{"value":"2019-07-10T10:26:04.000Z","timeStamp":1562754371937}
  },
  "identity":{"id":"did:3:bafyreietqryrtsm7tgw6dghp3lbdrwuk3qim3gtidvxp64s2q2g4lvexuu",
  "type":"3ID",
  "publicKey":"04f7c248b3805a86c53bb218c19c70778018cc35f0c56edaa55d5adc9e010160e5642f16b67b730984708942b4514f2e510d956a424acee0de97131e70fabcd16b",
  "signatures":{"id":"30440220285e40893117e13a7464b30b9388f18b298659ab86d9e37bb2d2cb34a432ccb002200acaf4f2730ba8ac98eac3bc2a39577813c80afeee79ff01b33341888e6e7c16","publicKey":"8vdl2Q305Be586Wt1aSQz8Jmpzu_TLCABZRWDh6m24gDc3Y23yOV0qPoFlOkFpXdTCXZ2tQ-YDFO8cdwgInK7Q"}}}
```

Seems to be related to the issue we where having at some point with `memberSince` being stored in a way which caused signatures to be invalid. I don't remember the exact problems it was causing however. @zachferland might know more. 
Does this cause the store not to load? If so why?

To replicate this issue use the code below:

```js
const Ipfs = require('ipfs')
const Replicator = require('3box/src/replicator')
const KVStore = require('3box/src/keyValueStore')
const registerResolver = require('3id-resolver')
const Identities = require('orbit-db-identity-provider')
const { OdbIdentityProvider } = require('3box-orbitdb-plugins')
Identities.addIdentityProvider(OdbIdentityProvider)


// nates rootstore
const ROOTSTORE_ADDRESS = '/orbitdb/QmUc9LYEjTAE1SKVB4abA6SE8M82WG1PxaiDJsTYnXgimj/12200d2d8d787aa61cb724fd57048a79a8c7c8dab502baec9a26e003db384dab8e97.root'

let ipfs = new Ipfs({ EXPERIMENTAL: { pubsub: true } })
ipfs.on('ready', async () => {
  registerResolver(ipfs)
  replicator = await Replicator.create(ipfs)
  await replicator.start(ROOTSTORE_ADDRESS, { profile: true })
  console.log('loaded')
  await replicator.rootstoreSyncDone
  console.log('rootSynced')
  console.log(replicator.rootstore.all.map(e => e.payload.value))
  await replicator.syncDone
  console.log('full sync')
  console.log(replicator._stores)
})
```

**Comment by zachferland** [comment]
I can find what that last problem was, but yeah sounds the same where the entry was serialized different on writes and verifications causing the sig verif to fail (the date object specifically being serialized differently in diff env). Api node would work since entry sigs no verified there (assuming verif before)

I remember we just made fix to serialize properly, and didnt actually make fix in orbit to force a cannonical serialization. but not sure what that fix would be, since orbit will just try toString() on anything and only throw if no such func available

**Comment by oed** [comment]
Ok, I don't get why it breaks orbitdb though. Couldn't it just not load that entry?

**Comment by zachferland** [comment]
yeah it should, i think we also talked about making that fix to orbit last time as well, because yeah the payload of an entry should never stop it from being able to open it. I can probably make an orbit issue/pr for that

**Comment by oed** [comment]
Prefect, thanks!

**Comment by oed** [comment]
@msterle I assigned this to you for now. If you have some extra time this sprint you can look into this.

**Comment by zachferland** [comment]
The potentially related issues 
https://github.com/3box/3box-js/issues/524
https://github.com/3box/3box-js/issues/529

Was originally not further worked on since a very minimal number of accounts would have been effected, should confirm is this is actually one of them that has one of these entries.

**Comment by michaelsena** [comment]
@oed to follow up

**Comment by msterle** [comment]
fixed by deleting public store's remote heads from orbit db cache in production. waiting confirmation from user that they have deleted their local data and the fix works.

**Comment by msterle** [comment]
Tried just deleting some orbit-db caches (as above), but didn't solve the problem. Ended up deleting all caches and entries in the address db, and problem was resolved. 

Keeping above AWS resources in case we need access to the caches again, but stopping the EC2 instance to not incur charges.
