### ISSUE TITLE
Change Cache to store address -> profile instead of rootAddress -> profile. 

### ISSUE THREAD

**Issue by zachferland** [3box/3box-pinning-node#32]
Cache the requests this way so that it also does not have to make request to address server if there is a cache hit, further decreasing request time. Was originally implemented rootAddress -> profile since it did not make request to address server in first iteration.

**Comment by oed** [comment]
Ideally we'd store the link "address -> DID" if the proof is present in the users 3box (it should always be stored there). Then we can compute the rootStoreAddress from the DID deterministicly. 
I'd also like this to be queryable from pubsub, which removes the reliance of any particular server.

**Comment by zachferland** [comment]
this is for the redis cache that caches the 'cache service', are you thinking about the same thing? storing the profile string is mostly what speeds up reqs when there is cache hits since it doesn't have to compute anything or initialize a store to read
