### ISSUE TITLE
Bug: uninitialized boxes hang the cache service

### ISSUE THREAD

**Issue by lsenta** [3box/3box-pinning-node#94]
How I produced this bug:
I was testing the pinning service, I connected to a dev pinner node and queried my store.

Now accessing my store will hang the server and produce a 504
https://ipfs-dev.3box.io/profile?address=0x70509caaf30cd92d5f14ddcf98e84e1b38f10a4d

Here's the pinning server logs:
```
0|node   | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
0|node   | TypeError: Cannot read property 'payload' of undefined
0|node   |     at pubStoreFromRoot (/home/ec2-user/3box-pinning-server/src/pinning.js:63:34)
0|node   |     at EventEmitter.openDBs.(anonymous function).db.events.on (/home/ec2-user/3box-pinning-server/src/pinning.js:136:9)
0|node   |     at EventEmitter.emit (events.js:182:13)
0|node   |     at FeedStore.load (/home/ec2-user/3box-pinning-server/node_modules/orbit-db-store/src/Store.js:219:17)
```

I believe this is caused by accessing a box that have not been initialized by 3box. Its content is empty and crashes the server.

**Comment by oed** [comment]
We should try to reproduce this in the 3box-services-box environment.
