### ISSUE TITLE
Add support for DID in REST API

### ISSUE THREAD

**Issue by oed** [3box/3box-pinning-node#98]
Right now we only support calling the rest api methods with ethereum addresses. We should add support for calling these methods with DIDs as well. 

Affected methods
* profile
* profileList
* space
* list-spaces

**Comment by oed** [comment]
Here is the code for uncompressing a public key https://github.com/bitcoin-core/secp256k1/issues/330#issuecomment-146098519

**Comment by lsenta** [comment]
Do we have instances of using DIDs to access data? I couldn't find any in the 3box-js library.

I'm not sure where I should use the uncompress code:

The content of the DID is:
```json
{
  "version": 1,
  "signingKey": "02d1f48e3d5c52954a01f1aa104bad1a22e2eed6ecbd4961737fbffa8d75457cd4",
  "managementKey": "0x3334d0c1fd88529a1285a5f3c9cd71b382684073",
  "asymEncryptionKey": "/MklZEmpCWWbUL/n5qnzLfEo6K0rtrtOrp60qNzrgVU="
}
```

Which when resolved gives:

```js
{ '@context': 'https://w3id.org/did/v1',
  id: 'did:muport:QmNQLKvMqGrDCrzmFS2C5p2JaRZ7bk6DqY7RJinhJoVxVT',
  publicKey:
   [ { id:
        'did:muport:QmNQLKvMqGrDCrzmFS2C5p2JaRZ7bk6DqY7RJinhJoVxVT#signingKey',
       type: 'Secp256k1VerificationKey2018',
       owner: 'did:muport:QmNQLKvMqGrDCrzmFS2C5p2JaRZ7bk6DqY7RJinhJoVxVT',
       publicKeyHex:
        '02d1f48e3d5c52954a01f1aa104bad1a22e2eed6ecbd4961737fbffa8d75457cd4' },
     { id:
        'did:muport:QmNQLKvMqGrDCrzmFS2C5p2JaRZ7bk6DqY7RJinhJoVxVT#managementKey',
       type: 'Secp256k1VerificationKey2018',
       owner: 'did:muport:QmNQLKvMqGrDCrzmFS2C5p2JaRZ7bk6DqY7RJinhJoVxVT',
       ethereumAddress: '0x3334d0c1fd88529a1285a5f3c9cd71b382684073' },
     { id:
        'did:muport:QmNQLKvMqGrDCrzmFS2C5p2JaRZ7bk6DqY7RJinhJoVxVT#encryptionKey',
       type: 'Curve25519EncryptionPublicKey',
       owner: 'did:muport:QmNQLKvMqGrDCrzmFS2C5p2JaRZ7bk6DqY7RJinhJoVxVT',
       publicKeyBase64: '/MklZEmpCWWbUL/n5qnzLfEo6K0rtrtOrp60qNzrgVU=' } ],
  authentication:
   [ { type: 'Secp256k1SignatureAuthentication2018',
       publicKey:
        'did:muport:QmNQLKvMqGrDCrzmFS2C5p2JaRZ7bk6DqY7RJinhJoVxVT#signingKey' } ],
  muportData: {} }
```

It looks like I want to use this did to find the management key which is the ethereum address of the owner. Am I missing something?

**Comment by oed** [comment]
1. The signingKey is the compressed public key, this should be uncompressed with the code I provided.
2. Get the name of the DB by doing this:
  a. Get the muport fingerprint like this: https://github.com/3box/3box-js/blob/develop/src/3id/index.js#L59 (sha256 of muport DID encoded as a multihash)
  b. You can then get the rootStore name like this: https://github.com/3box/3box-js/blob/develop/src/3box.js#L75
3. Use this function to generate the orbitdb Address: https://github.com/orbitdb/orbit-db/blob/master/src/OrbitDB.js#L279
